#!/bin/bash

# Runs an attack on a single TRAP unit and verifies the extracted key. 

trapFabricBuilder 1 1 ioMap.csv -o trapNAND2 #-m 5

satAttack trapNAND2.py trapNAND2_io.csv twoInputGates.v nand2 -fz
# Alternative version where TRAP fabric model is hand-written instead of generated by trapFabricBuilder
#satAttack trapUnitHandwrittenPL.py trapUnitHandwrittenPL_io.csv twoInputGates.v nand2 -fz

satVerify -z trapNAND2.py nand2PL.py trapNAND2_io.csv work/extracted_key.csv
# Alternative version for verifying handwritten model's solved bitstream
#satVerify -z trapUnitHandwrittenPL.py nand2PL.py trapUnitHandwrittenPL_io.csv work/extracted_key.csv
